# Exercise 1.A NumPy: Manipulating Arrays

In [76]:
import numpy as np

## Looping Through Arrays

**Create a variable named arrA as a two-dimensional array containing (11, 12, 13) and (14, 15, 16) then print arrA**

In [77]:
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)
print(type(arrA))
# nested lists create rows and columns, making it 2D.
# simply having [] creates a singular row list, making it 1D.
# However, [[]] creates a 2D array with one row + one column.
# Python's version of a spreadsheet table.

[[11 12 13]
 [14 15 16]]
<class 'numpy.ndarray'>


**Loop through the first dimension of arrA (i.e. for x in arrA) and
print each element multiplied by 2.**

In [78]:
# Loop through the first dimension of arrA (i.e. for x in arrA) and
# print each element multiplied by 2.

for x in arrA:
    print(x * 2)

# Each row is x, so I multiply each row by 2, which multiplies each element in the row by 2.
# Also, NumPy already applies the multiplication to each element in the array,
# so I don't have to loop through each row.

[22 24 26]
[28 30 32]


**Loop through the second dimension of arrA (i.e. for y in x) and
print each element multiplied by 2**

In [79]:
for x in arrA:
    for y in x:
        print(y * 2)

# This loops through each value. Also, the x is the row, and y is the value in the row.
# So, I multiply each value by 2.

22
24
26
28
30
32


First loop: works the code row by row, treating the values inside each list as a single unit.
So, each arrA(aka rows) are printed * 2.

Second Row: the code goes one level deeper and loops through each individual value inside the rows.
It prints each number * by 2 separately.

The key difference is that the first loop works at the ROW level (first dimension), while the second loop works at the VALUE level (second dimension), giving more detailed control over each value.

**Again loop through the second dimension of arrA (i.e. for y
in x), but this time, assign x*2 to a variable named loop_result. Add another line
of code to print loop_result, then add a comment to the cell to explain how/why
this result is different.**

In [80]:
for x in arrA:
    for y in x:
        loop_result = x * 2
    print(loop_result)

[22 24 26]
[28 30 32]


Issue: I keep accidentally typing the print statement in the wrong loop, which only prints the last value of the row multiplied by 2.
Indentation is something I need to be careful with, especially when I code loops.
The inner dimension was giving me triple the output, so I had to move the print statement outside the inner loop() onto the second dimension to get the correct output.

The output is the same as the previous code cell, with the difference that the print statement is outside the inner loop,
so it only prints the result of multiplying the row by 2 once PER ROW, instead of once PER VALUE in the row.
This keeps the values within the same row together.

## Joining and Stacking Arrays

**Create variable joined_array_1 and assign it the value of arrA concatenated
with arrA on axis=0 (the default axis). Print joined_array_1**

In [81]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


The axis is by default 0, so it doesnt necessarily need to be added but it helps me practice.
Also, concatenating arrays helps "glue" multiple arrays together.

(axis = 0) helps the code JOIN the arrays vertically by rows.
(axis = 1) helps the code JOIN the arrays horizontally by columns.

**Create variable joined_array_2 and assign it the value of arrA concatenated
with arrA on axis=1. Print joined_array_2.**

In [82]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


Now, (axis=1) joins the arrays horizontally, adding more columns to each row elongating is sideways.

**Create variable stacked_array_1 and assign it the value of joined_array_1
stacked with joined_array_1 on the default axis. Print stacked_array_1.**

In [83]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1), axis=0)
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


Stacking combines arrays along a new axis, adding an extra dimension (layers) to the output.

**Create variable stacked_array_2 and assign it the value of joined_array_1
stacked with joined_array_2 on the default axis. What error message do you
get? Add a comment to the cell to explain the error that comes back?**

In [84]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2), axis=0)
print(stacked_array_2)

ValueError: all input arrays must have the same shape

Error happens because the arrays don't have matching shapes for stacking. 
ChatGPT suggested to use print(joined_array_1.shape) / print(joined_array_2.shape) to confirm arrays are compatible prior to combining...

In [ ]:
print(joined_array_1.shape)
print(joined_array_2.shape)

(4, 3)
(2, 6)


The shape of joined_array_1 is (4, 3) because it has 4 rows and 3 columns.
The shape of joined_array_2 is (2, 6) because it has 2 rows and 6 columns.
This shows that the axis=0 concatenation adds rows, while axis=1 concatenation adds columns.

**Create variable another_joined_array and assign it the value of
joined_array_1 concatenated with arrA. Print another_joined_array.**

In [ ]:
another_joined_array = np.concatenate((joined_array_1, arrA), axis=0)
print(another_joined_array)

(4, 3)
(2, 3)
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


`Print(joined_array_1.shape)` *Output: (4, 3)*
`Print(arrA.shape)` *Output: (2, 3)*

Both arrays have the same number of columns, so they can be joined along axis 0 (rows). Again, I'm just defining the arrays as concatenated or "glued" on the default axis.

**Create variable another_2 and again assign it the value of joined_array_1
concatenated with arrA, but this time on axis=1. What happens when you try to run
this? Add a comment to the cell to paraphrase the error message in your own
words**

In [ ]:
print(joined_array_1.shape)
print(arrA.shape)
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)


(4, 3)
(2, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

This code gives me an error message because `axis=1` joins *horizontally*. So, when the output of each array is placed side by side the rows aren't the same, but not necessarily do the columns need to align. 

**Create a cell with three new variables (named as you choose). In each variable, use
either the hstack(), vstack(), or dstack() function to stack arrA with arrA.
Add a comment after each that explains what the function is doing. Print the results
of each variable**

In [86]:
variable_a = np.hstack((arrA, arrA))
print(variable_a)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


`hstack()` joins arrays horizontally along *column* axis (each array has the same number of columns/ adds more columns)

In [90]:
variable_b = np.vstack((arrA, arrA))
print(variable_b)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


`vstack()` joins arrays vertically along *row* axis (also adds more rows)

In [93]:
variable_c = np.dstack((arrA, arrA))
print(variable_c)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


`dstack()` joins along height/depth (this creates an extra dimension/layer)

## Splitting Arrays

**Create variable splitsky and assign it the value of joined_array_1 split into 2.
Print the variable. Then add a comment to the cell to describe the result: how many
arrays? Of how many dimensions each?**

In [95]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


The `array_split()` divides `joined_array_1` into two separate arrays each resulting array is still 2D because they contain rows AND columns. (Think of it as an excel sheet)

**Create variable spliterino and assign it the value of joined_array_1 split
into 3. Print the variable. Then add a comment to the cell to describe the result: how
many arrays? Of how many dimensions each?**

In [96]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


Similar to above.. The `array_split()` divides `joined_array_1` into 3 arrays each split array is still 2D because they still contain rows and columns.
Also, NumPy attempts to distribute the rows as evenly possible.

 ## Searching and Replacing Array Values

**Create variable result_1. For the value of this variable, use where() to find each even number within arrA (hint, you’ll need to write a condition using %
and ==). If the condition is met, print the value from arrA; if not met, print 'odd'.**

In [98]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


If a value in arrA is even, it keeps the original number, but if the value is odd, it gets replaced with the word 'odd'.
Basically reads as: `np.where(condition, value_if_true, value_if_false)`

## Sorting and Filtering Arrays

**Create variable arrB as a 2-D array including the values (7,6), (13,5), and (7,3).
Create another variable, arrB_sorted, and assign it the sorted value of arrB.
Print arrB_sorted.**

In [104]:
arrB = np.array([
    (7, 6),
    (13, 5),
    (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


The `np.sort()` sorts the values in each row from smallest to largest, but it only sorts by row not the entire list.

**Finally, let’s filter arrB using conditional logic. Start the cell with a print statement
to again print the contents of arrB. Then create variable z with the value arrB < 7
to look for values less than 7. Next create variable arrC, and assign it arrB[z].
Print arrC**

In [106]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


The z stores True/False values depending if each number is < 7. The `arrB[z]` filters the array and keeps only the values that match the condition I ask for is True.

**Applying the same sort of structure, how would you create a new conditional logic
filter y to look for values greater than or equal to 7? Follow similar steps as above to
create a new variable arrD to hold the filtered results, and print arrD**

In [108]:
y = arrB >= 7

arrD = arrB[y]

print(arrD)

[ 7 13  7]


The  y stores True/False values for numbers >= 7. The `arrD` keeps only the values that match the condition, so it only keeps `True` values.

How its read: `condition = array comparison
filtered_array = array[condition]`