# Exercise 1.B NumPy Random

In [32]:
import numpy as np

## Generating Random Numbers

**Create a variable named r_1 that contains a random set of integers between 1 and
20 with a size of 2 elements. Print r_1.**

In [33]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[ 2 16]


This generates two random integers(whole numbers) between 1 and 20. This is also useful in the real world to help generate fake customer_id or fake testing_data. Each time this code is ran the output will re-gerate a different output.

**Create a variable named r_2 that contains a random set of integers between 1 and
20 with a size of 1 row, 2 columns. Print r_2.**

In [34]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[18 14]]


I did get a little confused so I had AI generate a quick way to remember: `np.random.randint(low, high, size=...)` uses range + shape.

**Create a variable named r_3 that contains a random set of floats between 0 and 1
with a size of 2 rows, 1 columns. Print r_3.**

In [35]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.34543588]
 [0.80976464]]


This code generates random float values between 0 and 1, along with 2 rows and 1 column.
I did get a little confused and I had AI generate a quick way to remember: `np.random.rand(rows, columns)` only shapes go inside.

**Create a variable named r_4 that contains a random set of integers between 20
and 100 with a size of 4 rows, 5 columns. Print r_4.**

In [36]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[ 79  67  48  22  66]
 [100  74  79  67  88]
 [ 37  70  85  40  87]
 [ 48  47  55  23  82]]


**Create a variable named r_5 that contains a random set of floats between 0 and 1
with a size of 4 rows, 5 columns. Print r_5.**

In [37]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.72442746 0.60336106 0.92660344 0.40455254 0.20168625]
 [0.56241951 0.32861474 0.36988998 0.08511503 0.87434524]
 [0.37930777 0.56511573 0.39548152 0.03752735 0.15787323]
 [0.45480256 0.04981447 0.5575737  0.96241065 0.18406663]]


## Generating Random Choices from an Array

**Create a variable named students and assign it a 1-D array containing the names
of 12 of your classmates**

In [38]:
students = np.array([
    'Cagla', 'Mina', 'Sultan', 
    'Maritza', 'Paola', 'Julissa', 
    'Rodas', 'Godknows', 'Longley', 
    'Onur', 'Ceyhun', 'Jimmy'])
print(students)

['Cagla' 'Mina' 'Sultan' 'Maritza' 'Paola' 'Julissa' 'Rodas' 'Godknows'
 'Longley' 'Onur' 'Ceyhun' 'Jimmy']


**Create a variable named call_on and use it to choose one random selection from
students. Print call_on.**

In [39]:
call_on = np.random.choice(students)
print(call_on)

Longley


**Create a variable named breakout_groups and use it to choose a random
sampling from students that is 3 rows, 4 columns in size. Print breakout_groups and examine the results – would this be an effective way to
assign breakout groups? Why or why not?**

In [40]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

[['Mina' 'Godknows' 'Rodas' 'Rodas']
 ['Cagla' 'Rodas' 'Paola' 'Julissa']
 ['Onur' 'Maritza' 'Julissa' 'Paola']]


No, its not effective because the values may duplicate/repeat. Perhaps, If I used a different formula to distinguish each unique student name I'd be able to factor in skill level, participation, or balanced group composition. A better approach would be to shuffle the list and then evenly split it into groups.

**Create a variable named call_on_weighted and use it to choose make five
random selections from students, but this time assign different probability values
that will determine how likely each student is to be selected. At least one student
should have a zero likelihood of being called on, and at least one student should
have a 30% likelihood of being called on. Distribute other probability values as you
choose, and in a comment, explain the p values you assigned to each student. Print
call_on_weighted**

In [ ]:
call_on_weighted = np.random.choice(students, size=5, p=[0.25, 0.10, 0.06, 0.08, 0.10, 0.10, 0.05, 0.05,0.10, 0.05, 0.02, 0.04])
print(call_on_weighted)

['Rodas' 'Paola' 'Godknows' 'Sultan' 'Longley']


 p assigns different probabilities for how likely each student is to be selected.The first student has the highest chance at 25%, while some students have much lower chances the probabilities must match the number of students and add up to 1.0

## Generating a Normal Distribution

**Create a variable named bell_curve and assign it a random distribution for
which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
the returned array is 4 rows by 5 columns. Print bell_curve**

In [46]:
bell_curve=np.random.normal(10,5,(4,5))
print(bell_curve)

[[13.7453239   3.11649083  5.5150528   9.99734733  6.94284927]
 [ 8.01225276 11.21212832  8.98335632  5.15491486  7.47729483]
 [12.41127187  7.42588001  5.65888142  4.43007737 14.30214616]
 [ 3.67970716  7.04706638  6.60643636 10.39040788  7.8765364 ]]
