# Exercise 1.C Performing operations on arrays

In [183]:
import numpy as np

 ## Sample Arrays

**Create five variables containing random sample arrays to work with,
copying over the expressions you used for variables r_1 through r_5 in the
notebook for Exercise 1.B (NumPy Random)**

In [184]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

**print the current value of r_4**

In [185]:
print(type(r_4))
print(r_4)

<class 'numpy.ndarray'>
[[54 74 20 58 50]
 [59 32 98 86 80]
 [38 90 29 40 66]
 [28 90 36 63 43]]


**Use `np.random.shuffle` to shuffle the values in r_4. Then print r_4 again to view
the results**

In [186]:
np.random.shuffle(r_4)
print(r_4)

[[28 90 36 63 43]
 [54 74 20 58 50]
 [59 32 98 86 80]
 [38 90 29 40 66]]


**Looking at the results of the previous code block, how were the elements of the
array shuffled?**

The only shuffle() did to the code was move the order of the rows. Values were kept in the same column, however each entire row block was shuffled.

**Create a new variable named new_shuffle, and assign it the value of a random
permutation of r_4. Print new_shuffle, and then print r_4 again to compare
values**

In [187]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

[[59 32 98 86 80]
 [38 90 29 40 66]
 [28 90 36 63 43]
 [54 74 20 58 50]]


**Add a markdown cell and briefly describe in your own words, when would you use
shuffle versus permutation?**

- `shuffle()`
1. rearranges array directly
2. changes the integrity of the original ovewritting the array
3. doesn't make a backup copy because changes occur on the value itself
4. WORKPLACE EXAMPLE: shuffling customer records before model training

- `permutation()`
1. compares shuffled data vs. original data
2. doesnt change original but makes a COPY of the original array shuffled
3. preserves the original array unchanged
4. WORKPLACE EXAMPLE: running experiments without modifying the original data

## Mathematical Operations

**Print r_1 and r_2 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_2, using the add function. Also
print the shape of the result.**

In [188]:
print(r_1)
print(r_1.shape)


[1 4]
(2,)


In [189]:
print(r_2)
print(r_2.shape)

[[18 12]]
(1, 2)


In [190]:
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[[19 16]]
(1, 2)


**Print r_1 and r_3 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_3, using the add function. Also
print the shape of the result.**

In [191]:
print(r_1)
print(r_1.shape)

[1 4]
(2,)


In [192]:
print(r_3)
print(r_3.shape)

[[0.17301677]
 [0.10593671]]
(2, 1)


In [193]:
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[[1.17301677 4.17301677]
 [1.10593671 4.10593671]]
(2, 2)


**Print r_2 and r_4 again as starting values, and also print the shape of each using
the .shape attribute. Then print the result of r_2 plus r_4, using the add function.
Also print the shape of the result.**

In [194]:
print(r_2)
print(r_2.shape)

[[18 12]]
(1, 2)


In [195]:
print(r_4)
print(r_4.shape)

[[28 90 36 63 43]
 [54 74 20 58 50]
 [59 32 98 86 80]
 [38 90 29 40 66]]
(4, 5)


In [196]:
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

- `r_2` has a shape of (1,2), only has 1 row and 2 columns.
- `r_4` has a shape of (4,5), only has 4 rows and 5 columns.

This code cannot run and returns an error because the shapes of each array don't fit and for Numpy the array shape must align in order for the function to operate.

**Create an expression to illustrate what happens when you add r_1 and r_4. What
is the error message? How about adding r_2 or r_3 to r_4? Add a comment to the
cell with your findings.**

In [ ]:
print(np.add(r_1, r_4))
print(np.add(r_1, r_4).shape)

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

Similar error as the previous code.
- r_1 has a shape of (2,), only contains 2 values in a one-dimensional array.
- r_4 has a shape of (4,5), only contains 4 rows and 5 columns.

**Show what happens if you add np.array([1]) to r_4.**

In [197]:
np.add(np.array([1]), r_4)

array([[29, 91, 37, 64, 44],
       [55, 75, 21, 59, 51],
       [60, 33, 99, 87, 81],
       [39, 91, 30, 41, 67]])

This works because the array [1] contains a single value. NumPy broadcasts that one value across every element in r_4.

Since a single value can stretch to match any array shape, 1 gets added to every number in r_4.

**Show what happens if you add np.array([[1]]) to r_4.**

In [198]:
np.add(np.array([[1]]), r_4)

array([[29, 91, 37, 64, 44],
       [55, 75, 21, 59, 51],
       [60, 33, 99, 87, 81],
       [39, 91, 30, 41, 67]])

This also works because [[1]] is a 2-dimensional array with shape (1,1). NumPy can still broadcast this single value across all rows and columns of r_4.

Even though it is technically 2D, it still only contains one value so NumPy stretches it across the entire array.

**Show what happens if you add np.array([1,1,1,1,1]) to r_4.**

In [199]:
np.add(np.array([1,1,1,1,1]), r_4)

array([[29, 91, 37, 64, 44],
       [55, 75, 21, 59, 51],
       [60, 33, 99, 87, 81],
       [39, 91, 30, 41, 67]])

This works because the array has 5 values, which matches the 5 columns in r_4.

NumPy broadcasts the row across each row of r_4 and adds the values column-by-column. Since the dimensions align correctly, no error occurs.

**What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the
cell with the error message this produces.**

In [200]:
np.add(np.array([[1],[1]]), r_4)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

This returns an error because the shapes (2,1) and (4,5) do not match for broadcasting.

The 1 column can stretch to fit 5 columns, but 2 rows cannot stretch to fit 4 rows, so NumPy cannot add the arrays together.

**Explain how broadcasting works to combine the values of two arrays. Using the add function, what gets added to what?
What determines the shape of the resulting array?**

Broadcasting lets NumPy combine arrays of different shapes by stretching the smaller array to fit the bigger one when possible.

The add() function allows the values to be added together element by element. If one array is smaller, NumPy repeats or stretches those values across the larger array.

The final shape usually matches the larger array, as long as the dimensions are compatible.

## Rounding

**Print r_3 to display the values you’ll be working with for the next few cells.**

In [201]:
print(r_3)

[[0.17301677]
 [0.10593671]]


**Round the values in r_3 using trunc.**

In [202]:
np.trunc(r_3)

array([[0.],
       [0.]])

**Round the values in r_3 using fix.**

In [203]:
np.fix(r_3)

array([[0.],
       [0.]])

**Round the values in r_3 using floor.**

In [204]:
np.floor(r_3)

array([[0.],
       [0.]])

**Round the values in r_3 using ceil.**

In [205]:
np.ceil(r_3)

array([[1.],
       [1.]])

**Round the values in r_3 using round, to 2 decimal places.**

In [206]:
np.round(r_3, 2)

array([[0.17],
       [0.11]])

## Cumulative Operations

**Print r_4 to display the values you’ll be working with for the next few cells.**

In [208]:
print(r_4)

[[28 90 36 63 43]
 [54 74 20 58 50]
 [59 32 98 86 80]
 [38 90 29 40 66]]


**Print the sum of all values in r_4.**

In [209]:
np.sum(r_4)

np.int64(1134)

**Print the sum of elements along the 0 axis for r_4.**

In [207]:
np.sum(r_4, axis=0)

array([179, 286, 183, 247, 239])

**Print the sum of elements along the 1 axis for r_4.**

In [210]:
np.sum(r_4, axis=1)

array([260, 256, 355, 263])

**Print the cumulative sum (rolling total) of values in r_4.**

In [211]:
np.cumsum(r_4)

array([  28,  118,  154,  217,  260,  314,  388,  408,  466,  516,  575,
        607,  705,  791,  871,  909,  999, 1028, 1068, 1134])

**Print the cumulative sum (rolling total) of values along the 0 axis for r_4**

In [212]:
np.cumsum(r_4, axis=0)

array([[ 28,  90,  36,  63,  43],
       [ 82, 164,  56, 121,  93],
       [141, 196, 154, 207, 173],
       [179, 286, 183, 247, 239]])

## Grocery Problem

**Create two new variables, bag1 and bag2. The first variable represents the
contents of a grocery bag, which contains two vegetables, three fruits, four boxes of
snacks, and no beverages. The second variable represents another grocery bag,
which contains no fruits, four vegetables, two beverages, and one box of snacks.
Assign an appropriate array to each variable that represents how many of each
category of item are in each bag. Print bag1 and bag2**

In [ ]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)
# match the total number of items in each bag to the correct category index.

[2 3 4 0]
[4 0 1 2]


In [223]:
print(f'The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.')

The first bag contains 9 items, and the second bag contains 7 items.


**Write an expression to calculate the total number of items in each bag, and print the
result in the form of a sentence: The first bag contains __ items, and the second bag
contains ___ items.**

In [224]:
totals = np.vstack((bag1,bag2))
print(totals)


[[2 3 4 0]
 [4 0 1 2]]


**Write an expression to calculate the total number of items in each category, and
print the result in the form of a sentence: There are __ vegetables, __ fruits, __ boxes
of snacks, and __ beverages in the two grocery bags.**

In [239]:
category_totals = np.sum(totals, axis=0)
print(f'There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

**There are three people on your team: Ali, Ben, and Carla. Your squad went out to knock on doors each evening
last week, Monday through Friday, and now you are assembling that data.**

**Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on
Thursday, and 2 on Friday. Create a variable holding an array of these values.**

In [240]:
Ali = np.array([5, 4, 6, 4, 2])

- doors create a singular row
- vertically there's 5 columns for each day a door was knocked on

**Ben missed Monday because he was out of town. He reported knocking on 5 on
Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding
an array of Ben’s value**

In [241]:
Ben = np.array([0, 5, 5, 3, 4])

**Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4 on Friday. She was sick on Wednesday so missed that day. Create a variable holding an array of Carla’s values**

In [246]:
Carla = np.array([3, 6, 0, 3, 4])

**Compile the values reported by Ali, Ben, and Carla into a single array containing all door-knocks for the week, as all_knocks. Print the resulting array**

In [247]:
all_knocks = (np.array([Ali, Ben, Carla]))
# all_knocks = Ali + Ben + Carla
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


**Use all_knocks to calculate the total number of doors that each person knocked
on for the week, and also the total number of doors that the group collectively
knocked on. Print the results**

In [249]:
print(f'Ali knocked on {np.sum(Ali)} doors, Ben knocked on {np.sum(Ben)}, Carla knocked on {np.sum(Carla)}.')
print(f'Total doors knocked: {np.sum(all_knocks)}')

Ali knocked on 21 doors, Ben knocked on 17, Carla knocked on 16.
Total doors knocked: 54


**The organization you’re working with estimates that for every two door-knocks, one
of those people will actually turn out to vote. For your report to the organization,
what is the rolling total of estimated votes that your group was able to turn out, day
by day for last week? (Hint: Start with the rolling total by day, then multiply that array
by an appropriate value to get the result.**

In [250]:
daily_total = np.sum(all_knocks, axis=0)
rolling = np.cumsum(daily_total)
estimated_votes = rolling * 0.5
print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
